### PR TITLE
Added Features to Esp

### PR DESCRIPTION
**Pull request by therealvoric**
Yo Stan i added 1-2 Simple but fun features to the ESP.. :3

### CODE REVIEW

**Comment by therealvoric** [comment]
u can change the Rainbow :3  to Rainbow ofc
static BKCCheckbox __esp_rainbow = BKCCheckbox("Rainbow :3", false);

**Comment by therealvoric** [comment]
like idk what i clicked
it said ur 1 commit behind ur git and i pressed sync

**Comment by stanuwu** [comment]
doesnt build:
  ModuleESP.h(151, 27): [C3861] 'get_rainbow_color': identifier not found

**Review by therealvoric — COMMENTED** [review]
huh what is this

**Comment by therealvoric** [comment]
i fixed everything

**Comment by therealvoric** [comment]
fixed

**Comment by stanuwu** [comment]
merged

**Pull request merged**
